spring:
   cloud:
     azure:
       eventhub:
         connection-string: [Connection String]
         checkpoint-storage-account: vj1storageaccount
         checkpoint-access-key: [Access key for Checkpoint storage  container]
         checkpoint-container: wingtiptoyscontainer

     stream:
       bindings:
         consume-in-0:
           destination: eventhub-2
           group: $Default
         supply-out-0:
           destination: eventhub-2

       eventhub:
         bindings:
           consume-in-0:
             consumer:
               checkpoint-mode: MANUAL
       function:
         definition: consume;supply;
       poller:
         initial-delay: 0
         fixed-delay: 1000

azure:
  cosmos:
    uri: [URI of the CosmosDB]
    key: [Access key]
    database: Eventhubs
    container: events